### ISSUE TITLE
Image to describe the Store on docs

### ISSUE THREAD

**Issue by MarceloBorgesP** [railsblocks/railsblocks-theme#13]
We need an image like similar to this one, to describe the Store in our documentation:

![layouts](https://cloud.githubusercontent.com/assets/4267241/10315444/ba97668c-6c30-11e5-9a8c-77f5f188c8b8.jpg)

The image should divide the Store in Header, Page title and breadcrumb, Main content and Footer.

**Comment by MarceloBorgesP** [comment]
I would assign this to you @caiohdf but I think I don't have permission for it.

**Comment by caiohdf** [comment]
Hi @MarceloBorgesP 

Here is the image: 
![zertico](https://cloud.githubusercontent.com/assets/886330/10339903/02ab7fb8-6ce4-11e5-819a-fbe5665a6b4e.jpg)

**Comment by MarceloBorgesP** [comment]
Thanks @caiohdf!
