### ISSUE TITLE
Adding bower components to the theme

### ISSUE THREAD

**Issue by caiohdf** [railsblocks/railsblocks-theme#6]
## The need
We need to properly install (and of course) use the bower components in the theme.
Currently there are only 1 of 6 bower components installed and working properly. But we need to move on and get all the 6 working (only LESS is working at this point).

**Current list of bower components in the project**
<img width="200" alt="screen shot 2015-09-02 at 1 42 49 pm" src="https://cloud.githubusercontent.com/assets/886330/9637739/d5f65280-5178-11e5-9bcf-b11a7f91a863.png">

In order to assist other contributors to the project, I'm creating this issue so everyone can read a solution and then this issue will be turn in wiki contribution.

Thanks!

**Comment by fernandes** [comment]
@caiohdf could you please write a small wiki page about this process?

thank you

**Comment by caiohdf** [comment]
Yes, sure!

**Comment by fernandes** [comment]
:bow: !

**Comment by caiohdf** [comment]
Wiki page created: https://github.com/railsblocks/railsblocks-theme/wiki/How-to-add-external-components-to-the-theme

:octocat:

**Comment by fernandes** [comment]
great! :smile_cat:
